DATASET:
    train_list: ['PW3D', 'Human36M', 'MPII3D', 'MPII', 'COCO'] # 
    test_list: ['PW3D']
    input_joint_set: 'coco'
    target_joint_set: 'human36'
    workers: 16
    use_gt_input: False
    stride: 2

MODEL:
    name: 'LINK'
    input_shape: [384, 288]
    normal_loss_weight: 0.1 # 0.01 #
    edge_loss_weight: 20 # 0.01
    joint_loss_weight: 0.001 # 0.0012
    posenet_pretrained: True
    posenet_path: ''

TRAIN:
    print_freq: 20
    batch_size: 128
    shuffle: True
    begin_epoch: 1
    end_epoch: 150
    edge_loss_start: 2
    scheduler: 'step'
    lr: 0.000001
    lr_step: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 20, 40, 60, 80]
    lr_factor: 0.95
    optimizer: 'adam'
    wandb: True

AUG:
    flip: False
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False
